include: package:flutter_lints/flutter.yaml

analyzer:

  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    must_be_immutable: error

    


