name: sched
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter


  dartz: ^0.10.0
  # generators
  freezed_annotation: ^0.14.3
  json_annotation: ^4.3.0
  #state management
  flutter_bloc: ^7.3.2
  injectable: ^1.5.0
  get_it: ^7.2.0
  #firebase
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  google_sign_in: ^5.1.0
  cloud_firestore: ^3.1.0
  #testing
  firebase_auth_mocks: ^0.8.1
  mockito: ^5.0.16
  #helpers
  uuid: ^3.0.5
  auto_route: ^3.1.3
  validators: ^3.0.0
  kt_dart: ^0.10.0
  # UI
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.2.0
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  #generators
  freezed: ^0.14.2
  build_runner: ^2.1.2
  auto_route_generator: ^3.1.0
  json_serializable: ^6.0.1
  injectable_generator: ^1.4.1

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: "BrandonGrotesque Bold"
      fonts:
        - asset: assets/fonts/NeutraText-Bold.otf
    - family: "BrandonGrotesque Italic"
      fonts:
        - asset: assets/fonts/NeutraText-BoldItalic.otf
    - family: "BrandonGrotesque Book"
      fonts:
        - asset: assets/fonts/NeutraText-Book.otf

